Repository UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs, pull requests merged in 2022-01, with the labels that each got.

#14 Artefato de metodologias
  docs/assets/metodologia/discord.png
  docs/assets/metodologia/github.png
  docs/assets/metodologia/methodology_map.png
  docs/assets/metodologia/teams.png
  docs/assets/metodologia/telegram.png
  docs/assets/metodologia/zenhub.png
  docs/base/metodologia.md
  mkdocs.yml
Labels: documentation, waiting review

#12 Artefato de modelagem BPMN
  docs/assets/modelagem_bpmn/Diagrama_BPMN_1.png
  docs/assets/modelagem_bpmn/Diagrama_BPMN_2.png
  docs/assets/modelagem_bpmn/Diagrama_BPMN_3.png
  docs/assets/modelagem_bpmn/Diagrama_BPMN_4.png
  docs/assets/modelagem_bpmn/Diagrama_BPMN_5.png
  docs/assets/modelagem_bpmn/notacao_bpmn.png
  docs/base/modelagem_bpmn.md
  mkdocs.yml
Labels: documentation, waiting review

#16 Artefato Política de Contribuição e configurações diversas do repositório
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/duvida-template.md
  .github/ISSUE_TEMPLATE/hotfix_template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/pull_request_template.md
  README.md
  docs/base/politicas_de_contribuicao.md
  docs/reunioes/ata_25_01.md
  mkdocs.yml
Labels: documentation, waiting review

#17 Artefato de Entrevista
  docs/requisitos/elicitacao/entrevista.md
  mkdocs.yml
Labels: documentation, waiting review, elicitação

#20 Artefato Elicitacao Brainstorming
  docs/assets/requisitos/elicitacao/brainstorming.png
  docs/requisitos/elicitacao/brainstorming.md
  mkdocs.yml
Labels: documentation, waiting review, elicitação

#21 Artefato de Introspecção
  docs/base/metodologia.md
  docs/requisitos/elicitacao/introspeccao.md
  mkdocs.yml
Labels: documentation, waiting review, elicitação

#28 Artefato de Mapa Mental
  docs/assets/requisitos/preRastreabilidade/mapaMental.svg
  docs/assets/requisitos/preRastreabilidade/mapaMentalBrenno.png
  docs/assets/requisitos/preRastreabilidade/mapaMentalCarlos.png
  docs/assets/requisitos/preRastreabilidade/mapaMentalDenniel.png
  docs/assets/requisitos/preRastreabilidade/mapaMentalEduardo.jpg
  docs/assets/requisitos/preRastreabilidade/mapaMentalJoao.jpg
  docs/assets/requisitos/preRastreabilidade/mapaMentalPaulo.jpg
  docs/assets/requisitos/preRastreabilidade/mapaMentalRafael.png
  docs/assets/requisitos/preRastreabilidade/mapaMentalThiago.png
  docs/assets/requisitos/preRastreabilidade/mapaMentalVictor.jpg
  docs/assets/requisitos/preRastreabilidade/mapaMentalVitor.jpg
  docs/requisitos/preRastreabilidade/mapasMentais.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: documentation, pré-elicitação
